### PR TITLE
Modify inner select of full verify to sort by hash

### PR DESCRIPTION
**Pull request by ghost**
We ran into a case where the full hash of hashes was not matching between postgres and crdb, in spite of the rows all being identical, and the row hashes all being identical. The problem seems to have derived from the ordering of the hashed rows, and is fixed by ordering the rows by their hash instead of by their primary key.

### CODE REVIEW

**Review by rishmathur21 — APPROVED** [review]

**Comment by ghost** [comment]
So, it turns out that this does not solve the problem. I'm leaving this PR open in case I come with a better solution.

**Comment by cjfinnell** [comment]
> So, it turns out that this does not solve the problem. I'm leaving this PR open in case I come with a better solution.

Switching to `draft` to reflect this

**Comment by cjfinnell** [comment]
@jonathan-udacity can we close this?

**Comment by cjfinnell** [comment]
(didn't mean to close, but easily reversible if your answer is `no`)

**Pull request closed without merging**
