### PR TITLE
Initial review

### PR DESCRIPTION
**Pull request by cjfinnell**
[Monday item](https://udacity.monday.com/boards/1773996647/pulses/2050058025)

This work was spun out into a separate project (instead of bloating features for https://github.com/udacity/warp-pipe) following [this slack thread](https://udacity.slack.com/archives/C04Q6NZS5/p1642109154010500)

Since most of this work was done outside of our usual PR process, I've created this PR to merge into the `review` branch; once comments/changes/new commits are in and Approved, I'll merge those changes as a fresh PR into `main`.

(I would recommend viewing all files instead of per-commit; these commits show an exploratory method and have not been cleaned up to be a cohesive story pointing to the final product)

Changes from feedback will be put into additional PRs into the `main` branch:
- #3

### CODE REVIEW

**Comment by kunalyadwadkar** [comment]
Haven't yet gone through all of this, but why is this project forked from a public project called `pgverify` ? Apologies if this was already addressed in the group review time (which I couldn't get to).

**Comment by kunalyadwadkar** [comment]
The remaining LGTM but I'll wait to get some clarity on the source of this project first. 

Also, and this doesn't have to be part of the current PR, but the README should document how to run this. (and what to expect when we do run it).

**Comment by cjfinnell** [comment]
> Haven't yet gone through all of this, but why is this project forked from a public project called `pgverify` ? Apologies if this was already addressed in the group review time (which I couldn't get to).

This verification feature was originally slated to be included in https://github.com/udacity/warp-pipe, which forks from https://github.com/perangel/warp-pipe. After deciding that it wasn't a great fit for warp-pipe (could be characterized as feature bloat), I took the existing opensource pattern of `push initial MVP work to personal repo, fork to udacity, collaborate/iterate there`. I image that udacity won't be interested in maintaining this once the crdb migration is complete, and I'm not opposed to taking a stewardship role moving forward if other collaborators (i.e. crdb customers moving off of psql) are looking to use and tweak.

**Comment by kunalyadwadkar** [comment]
>  I image that udacity won't be interested in maintaining this once the crdb migration is complete, and I'm not opposed to taking a stewardship role moving forward if other collaborators (i.e. crdb customers moving off of psql) are looking to use and tweak. 

If you're looking to open source this, that's reasonable. Let's just make sure that we cross our t's and dot our i's there. I can set us up with Robin if you would like that. 

**Until then can you please mark the repo as private?**

**Review by kunalyadwadkar — APPROVED** [review]

**Review by cornerkitten — APPROVED** [review]
Looks good to me, since PRs #3 and #4 will address feedback (i.e. README and global vars) from last week's team review session.

**Pull request merged**
